/*
 * File: app/controller/Map.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.Map', {
    extend: 'Ext.app.Controller',

    config: {
        views: [
            'Viewport'
        ],
        refs: {
            gftmap: '#gftmap'
        },

        control: {
            "checkboxfield[name=SchweizerStaedteCheckbox]": {
                check: 'onCheckboxfieldCheck'
            }
        }
    },

    onCheckboxfieldCheck: function(checkboxfield, e, options) {
        console.log("controller function executed");
        this.createLayer(2741123);
    },

    createLayer: function(tableId) {
        var layer = new google.maps.FusionTablesLayer({
            query: {
                select: 'location',
                from: tableId,
            }
        });

        layer.setMap(this.getGftmap().getMap());
        console.log('createLayer controller function done');
    }

});