/*
 * File: app/view/Viewport.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Viewport', {
    extend: 'Ext.Container',

    config: {
        layout: {
            type: 'card'
        },
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'GFTPrototype'
            },
            {
                xtype: 'tabpanel',
                tabBar: {
                    docked: 'bottom'
                },
                items: [
                    {
                        xtype: 'panel',
                        layout: {
                            type: 'fit'
                        },
                        title: 'Karte',
                        iconCls: 'maps',
                        items: [
                            {
                                xtype: 'map',
                                id: 'gftmap',
                                mapOptions: {
                                    zoom: 5
                                },
                                useCurrentLocation: true
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        scrollable: 'true\n',
                        title: 'Ebenen',
                        iconCls: 'locate',
                        items: [
                            {
                                xtype: 'fieldset',
                                title: 'Ebenen',
                                items: [
                                    {
                                        xtype: 'checkboxfield',
                                        id: 'schweizerStaedteCheckbox',
                                        label: 'Schweizer Städte',
                                        name: 2741123
                                    },
                                    {
                                        xtype: 'togglefield',
                                        id: 'schweizerStaedteToggle',
                                        label: 'Schweizer Städte',
                                        name: 2741123
                                    },
                                    {
                                        xtype: 'sliderfield',
                                        disabled: true,
                                        id: 'schweizerStaedteEinwohner',
                                        label: 'Einwohner',
                                        name: 'Einwohner',
                                        increment: 1000,
                                        maxValue: 600000
                                    },
                                    {
                                        xtype: 'numberfield',
                                        disabled: true,
                                        id: 'populationValue',
                                        label: 'Einwohner',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'checkboxfield',
                                        id: 'coinCheckbox',
                                        label: 'Coin',
                                        name: 3107027
                                    },
                                    {
                                        xtype: 'togglefield',
                                        id: 'coinToggle',
                                        label: 'Coin',
                                        name: 3107027
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        ]
    }

});